baseURL = 'http://example.org/'
languageCode = 'ja-jp'
title = "Kanta's Blog"
theme = 'loveIt'

enableEmoji = true

[author]
  name = "Kanta Mori"
  email = "mrknt0088@gmail.com"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
  gitRepo = "https://github.com/morikann/"
  title = "Blog"
  description = "Flutter/iOS Enginner"

  [params.header]
    [params.header.title]
      name = "Blog"

  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "/images/profile.png"
      title = "Kanta's Blog"
      subtitle = "Flutter / iOS Enginner"

  [params.social]
    GitHub = "https://github.com/morikann/"
